blank_issues_enabled: false
contact_links:
  - name: GDevelop Discord
    url: https://discord.gg/rjdYHvj
    about: Discuss on the forum or on the Discord to get help with an example or create a new one.
  - name: GDevelop Forums
    url: https://forum.gdevelop-app.com
    about: You can also discuss examples on the forum.
